name: app_monitors
description: MBS Monitor Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  http: ^0.13.3
  logging: ^1.0.1
  lottie: ^1.1.0
  get: ^4.3.0
  get_storage: ^2.0.3
  pattern_formatter: ^2.0.0
  charts_flutter:
    git:
      url: git://github.com/google/charts.git
      path: charts_flutter
  charts_common: ^0.11.0
  flutter_svg: ^0.22.0
  firebase_core: "^1.5.0"
  firebase_messaging: "^10.0.5"
  flutter_local_notifications: ^8.1.1+2
  pull_to_refresh: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Fonts_AvertaStdCy
      fonts:
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-Black.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-BlackItalic.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-Bold.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-BoldItalic.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-Extrabold.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-ExtraboldItalic.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCy-Extrathin.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCy-ExtrathinItalic.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-Light.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-LightItalic.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-Semibold.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-RegularItalic.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-Regular.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-SemiboldItalic.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-Thin.otf
        - asset: assets/fonts/Fonts_AvertaStdCy/AvertaStdCY-ThinItalic.otf

    - family: IBM_Plex_Sans
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-BoldItalic.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-ExtraLight.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-ExtraLightItalic.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Italic.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Light.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-LightItalic.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-MediumItalic.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-SemiBold.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-SemiBoldItalic.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-Thin.ttf
        - asset: assets/fonts/IBM_Plex_Sans/IBMPlexSans-ThinItalic.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - assets/svgs/
    - assets/splash/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
